### ISSUE TITLE
Count down timer

### ISSUE THREAD

**Issue by zhvial** [micbay/RaceTimerAndController#7]
After less than minute is left on count down race timer, minute chars are not deleted and 01: minute is shown.
Video link below: 
https://youtu.be/AJK_NrQgwsg

**Comment by micbay** [comment]
This problem was due to some errors in the PrintClock() function and PrintSpanOfChars() functions related to calculating the print width.
As the total space needed to print the current time was reduced by a clock countdown from needing minutes to just needing seconds, the part of the clock no longer used was not being cleared.
I have updated the PrintClock() to properly calculate actual clock space used and thus, also the space that needs to be cleared when no longer used.
At the same time I changed the PrintSpanOfChars() to use 'int' variables instead of 'byte' variables so that negative positions can be considered. I don't think that was part of the problem here, but was done because negative position is a possibility.
Should be fixed now in the current master.
